module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    SET_PLAYER: 'SET_PLAYER',
    NEXT_PLAYER: 'NEXT_PLAYER',
    NEXT_INITIATIVE: 'NEXT_INITIATIVE',
    SET_INITIATIVE: 'SET_INITIATIVE',
    SET_MORALE: 'SET_MORALE',
    SET_VICTORY: 'SET_VICTORY'
};
