module.exports = {
	"logo": require('../res/logo.png'),
	"splash": require('../res/morale.jpg'),
	"menu": require('../res/hamburger-light.png'),
	"info": require('../res/info-light.png'),

	"british": require('../res/british-flag.png'),
	"american": require('../res/american-flag.jpg'),
	"french": require('../res/french-flag.png'),
	"first": require('../res/british-flag.png'),
	"second": require('../res/american-flag.jpg'),
	"tie": require('../res/tie.png'),

	"1": require('../res/1.png'),
	"2": require('../res/2.png'),
	"3": require('../res/3.png'),
	"4": require('../res/4.png'),
	"5": require('../res/5.png'),
	"Miss": require('../res/no-effect.png'),
	"AM": require('../res/morale-loss.png'),
	"R": require('../res/retreat.png'),
	"D": require('../res/disrupted.png'),
	"leader-casualty": require('../res/leader-casualty.png'),
	"pass": require('../res/pass.png'),
	"fail": require('../res/fail.jpg'),

	"refreshButton": require('../res/refresh-light.png'),
	"prevButton":	require('../res/ic_action_previous_item.png'),
	"nextButton": require('../res/ic_action_next_item.png'),
	"checked": require('../res/checked_checkbox.png'),
	"unchecked": require('../res/unchecked_checkbox.png'),

	"brandywine": require('../res/brandywine.jpg'),
	"germantown": require('../res/germantown.jpg'),
	"guilford": require('../res/guilford.jpg'),
	"monmouth": require('../res/monmouth.jpg'),
	"newtown": require('../res/newtown.jpg'),
	"pensacola": require('../res/pensacola.jpg'),
	"saratoga": require('../res/saratoga.jpg'),
	"savannah": require('../res/savannah.jpg')
};
